### PR TITLE
Add configuration for jsonnetfmt flags

### LINKED ISSUE #1: Configurable formatter options
Hi, your plugin is very useful, could you make the fmt arguments configurable though? Thanks. I have no experience with vscode plugins to make it myself.

### PR DESCRIPTION
**Pull request by mckunda**
Fixes #1

### CODE REVIEW

**Comment by stevenzyang** [comment]
@ashi009 Can someone take a look at this? Would be useful to get this merged

**Comment by ashi009** [comment]
> @ashi009 Can someone take a look at this? Would be useful to get this merged

I no longer work here. Even if this got merged I couldn't manage to release a new version.

**Comment by ywwg** [comment]
Does anyone own this repository? This would be a nice change to have in.

**Comment by itspngu** [comment]
> Does anyone own this repository? This would be a nice change to have in.

I [forked](https://github.com/itspngu/vscode-jsonnet-format) and [published](https://marketplace.visualstudio.com/items?itemName=itspngu.jsonnet-format) the thing.

**Pull request closed without merging**
